# Lendo arquivo e preparando para inclose5_CARM

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
import plot_classes_dataset as plt_dtset

def save_sorted_dtset(path, dt_name, r_ord, labels, save=False):
    dt = plt_dtset.Dataset(path, dt_name, r_ord, labels)
    ready_matrix = np.loadtxt(dt.path_filename)
    sorted_dt = dt.sort_matrix(ready_matrix, 'asc')
    if save:
        np.savetxt(path+dt_name+'_asc', sorted_dt, fmt='%u', delimiter=' ', newline='\n')
    return sorted_dt

h = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week','native-country', 'class' ]
data = pd.read_csv("/home/julia/Downloads/adult.data", names=h).replace(' ?', None)
data

39          State-gov   77516    Bachelors   13        Never-married  \
0      50   Self-emp-not-inc   83311    Bachelors   13   Married-civ-spouse   
1      38            Private  215646      HS-grad    9             Divorced   
2      53            Private  234721         11th    7   Married-civ-spouse   
3      28            Private  338409    Bachelors   13   Married-civ-spouse   
4      37            Private  284582      Masters   14   Married-civ-spouse   
...    ..                ...     ...          ...  ...                  ...   
32555  27            Private  257302   Assoc-acdm   12   Married-civ-spouse   
32556  40            Private  154374      HS-grad    9   Married-civ-spouse   
32557  58            Private  151910      HS-grad    9              Widowed   
32558  22            Private  201490      HS-grad    9        Never-married   
32559  52       Self-emp-inc  287927      HS-grad    9   Married-civ-spouse   

             Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0         Exec-managerial         Husband   White     Male      0   0   13   
1       Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2       Handlers-cleaners         Husband   Black     Male      0   0   40   
3          Prof-specialty            Wife   Black   Female      0   0   40   
4         Exec-managerial            Wife   White   Female      0   0   40   
...                   ...             ...     ...      ...    ...  ..  ...   
32555        Tech-support            Wife   White   Female      0   0   38   
32556   Machine-op-inspct         Husband   White     Male      0   0   40   
32557        Adm-clerical       Unmarried   White   Female      0   0   40   
32558        Adm-clerical       Own-child   White     Male      0   0   20   
32559     Exec-managerial            Wife   White   Female  15024   0   40   

        United-States   <=50K  
0       United-States   <=50K  
1       United-States   <=50K  
2       United-States   <=50K  
3                Cuba   <=50K  
4       United-States   <=50K  
...               ...     ...  
32555   United-States   <=50K  
32556   United-States    >50K  
32557   United-States   <=50K  
32558   United-States   <=50K  
32559   United-States    >50K  

[32560 rows x 15 columns]

In [97]:
test = pd.read_csv("/home/julia/Downloads/adult.test", names=h).replace(' ?', None)
test

age      workclass  fnlwgt      education  education-num  \
0       25        Private  226802           11th              7   
1       38        Private   89814        HS-grad              9   
2       28      Local-gov  336951     Assoc-acdm             12   
3       44        Private  160323   Some-college             10   
4       18        Private  103497   Some-college             10   
...    ...            ...     ...            ...            ...   
16276   39        Private  215419      Bachelors             13   
16277   64        Private  321403        HS-grad              9   
16278   38        Private  374983      Bachelors             13   
16279   44        Private   83891      Bachelors             13   
16280   35   Self-emp-inc  182148      Bachelors             13   

            marital-status          occupation     relationship  \
0            Never-married   Machine-op-inspct        Own-child   
1       Married-civ-spouse     Farming-fishing          Husband   
2       Married-civ-spouse     Protective-serv          Husband   
3       Married-civ-spouse   Machine-op-inspct          Husband   
4            Never-married   Machine-op-inspct        Own-child   
...                    ...                 ...              ...   
16276             Divorced      Prof-specialty    Not-in-family   
16277              Widowed      Prof-specialty   Other-relative   
16278   Married-civ-spouse      Prof-specialty          Husband   
16279             Divorced        Adm-clerical        Own-child   
16280   Married-civ-spouse     Exec-managerial          Husband   

                      race      sex  capital-gain  capital-loss  \
0                    Black     Male             0             0   
1                    White     Male             0             0   
2                    White     Male             0             0   
3                    Black     Male          7688             0   
4                    White   Female             0             0   
...                    ...      ...           ...           ...   
16276                White   Female             0             0   
16277                Black     Male             0             0   
16278                White     Male             0             0   
16279   Asian-Pac-Islander     Male          5455             0   
16280                White     Male             0             0   

       hours-per-week  native-country    class  
0                  40   United-States   <=50K.  
1                  50   United-States   <=50K.  
2                  40   United-States    >50K.  
3                  40   United-States    >50K.  
4                  30   United-States   <=50K.  
...               ...             ...      ...  
16276              36   United-States   <=50K.  
16277              40   United-States   <=50K.  
16278              50   United-States   <=50K.  
16279              40   United-States   <=50K.  
16280              60   United-States    >50K.  

[16281 rows x 15 columns]

Education-num is the same as education. Education can be removed.

OBS: Replace missing data to none, complete the none with a value

In [98]:
adult = pd.concat([data, test])
adult = adult.drop(columns=['education'])
np.where(adult['workclass'] == None)

(array([], dtype=int64),)

## Building new matrix (numerical)

In [99]:
catg = ['workclass', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'native-country']
num = ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week' ]

h = ['age', 'workclass', 'fnlwgt', 'education-num', 'marital-status', 'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week','native-country']

num_adult = pd.DataFrame([], columns=h)
num_adult[num] = adult[num]
num_adult

age workclass  fnlwgt  education-num marital-status occupation  \
0       39       NaN   77516             13            NaN        NaN   
1       50       NaN   83311             13            NaN        NaN   
2       38       NaN  215646              9            NaN        NaN   
3       53       NaN  234721              7            NaN        NaN   
4       28       NaN  338409             13            NaN        NaN   
...    ...       ...     ...            ...            ...        ...   
16276   39       NaN  215419             13            NaN        NaN   
16277   64       NaN  321403              9            NaN        NaN   
16278   38       NaN  374983             13            NaN        NaN   
16279   44       NaN   83891             13            NaN        NaN   
16280   35       NaN  182148             13            NaN        NaN   

      relationship race  sex  capital-gain  capital-loss  hours-per-week  \
0              NaN  NaN  NaN          2174             0              40   
1              NaN  NaN  NaN             0             0              13   
2              NaN  NaN  NaN             0             0              40   
3              NaN  NaN  NaN             0             0              40   
4              NaN  NaN  NaN             0             0              40   
...            ...  ...  ...           ...           ...             ...   
16276          NaN  NaN  NaN             0             0              36   
16277          NaN  NaN  NaN             0             0              40   
16278          NaN  NaN  NaN             0             0              50   
16279          NaN  NaN  NaN          5455             0              40   
16280          NaN  NaN  NaN             0             0              60   

      native-country  
0                NaN  
1                NaN  
2                NaN  
3                NaN  
4                NaN  
...              ...  
16276            NaN  
16277            NaN  
16278            NaN  
16279            NaN  
16280            NaN  

[48842 rows x 13 columns]

In [103]:
ord_enc = OrdinalEncoder()
num_adult[catg] = ord_enc.fit_transform(adult[catg]).astype(int)
num_adult.to_csv('new_adult_num', sep=' ', header=False, index=False)

# Label

In [101]:
adult.replace({'class' : { ' <=50K' : 0, ' >50K' : 1, ' <=50K.' : 0,  ' >50K.' : 1}}, inplace=True)

In [104]:
adult['class'].to_csv('new_adult_labels', sep=' ', header=False, index=False)

Tirar colunas só com zeros

In [127]:
df = pd.read_csv("adult/new_adult_num_mdlp",header=None, names=h, sep=' ')
df = df.drop(columns=['fnlwgt'])
df

age  workclass  education-num  marital-status  occupation  \
0        6          4              4               2           0   
1        7          4              4               1           2   
2        6          2              1               0           3   
3        7          2              0               1           3   
4        4          2              4               1           5   
...    ...        ...            ...             ...         ...   
48837    6          2              4               0           5   
48838    9          2              1               3           5   
48839    6          2              4               1           5   
48840    7          2              4               0           0   
48841    5          3              4               1           2   

       relationship  race  sex  capital-gain  capital-loss  hours-per-week  \
0                 1     3    1             1             0               2   
1                 0     3    1             0             0               0   
2                 1     3    1             0             0               2   
3                 0     2    1             0             0               2   
4                 5     2    0             0             0               2   
...             ...   ...  ...           ...           ...             ...   
48837             1     3    0             0             0               1   
48838             2     2    1             0             0               2   
48839             0     3    1             0             0               4   
48840             3     1    1            11             0               2   
48841             0     3    1             0             0               4   

       native-country  
0                   4  
1                   4  
2                   4  
3                   4  
4                   0  
...               ...  
48837               4  
48838               4  
48839               4  
48840               4  
48841               4  

[48842 rows x 12 columns]

In [128]:
from sklearn.preprocessing import OneHotEncoder

oe_style = OneHotEncoder()
oe_results = oe_style.fit_transform(df).astype(int)

oe_style.categories_

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([0, 1, 2, 3, 4]),
 array([0, 1, 2, 3, 4, 5, 6]),
 array([0, 1, 2, 3]),
 array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([0, 1, 2, 3, 4, 5]),
 array([0, 1, 2, 3]),
 array([0, 1]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18]),
 array([0, 1, 2, 3, 4, 5]),
 array([0, 1, 2, 3, 4])]

In [131]:
adult_discretized = pd.DataFrame(oe_results.toarray())

In [133]:
#adult_discretized.to_csv('new_adult_discretized', sep=' ', header=False, index=False)

# Ordenando a matriz

In [139]:
adult = np.loadtxt('adult/new_adult_discretized', dtype='bool')
adult.shape

(48842, 96)

In [142]:
path = 'adult/'
dt_name = 'new_adult_discretized'
r_ord = 0
labels = 'new_adult_labels'

adult_test_asc = save_sorted_dtset(path, dt_name, r_ord, labels)
adult_test_asc.shape

(48842, 96)