In [1]:
import pandas as pd
import numpy as np
import math

In [160]:
dt = pd.read_excel('Espectros_farmacos_5classes_08.02.2022_anonimizado.xlsx', engine='openpyxl')
dt

ID_number  GroupAED (1 - controles, 2 - responsivos, 3 - resistentes)  \
0          1.0                                                  1            
1          2.0                                                  1            
2          3.0                                                  1            
3          4.0                                                  1            
4          5.0                                                  1            
..         ...                                                ...            
172      131.0                                                  3            
173      140.0                                                  3            
174      175.0                                                  3            
175      141.0                                                  3            
176      142.0                                                  3            

     SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)  \
0                                                  1.0            
1                                                  1.0            
2                                                  1.0            
3                                                  1.0            
4                                                  1.0            
..                                                 ...            
172                                                4.0            
173                                                4.0            
174                                                4.0            
175                                                4.0            
176                                                4.0            

    Depressão (0 - não, 1 - sim)  \
0                              0   
1                              0   
2                              0   
3                              0   
4                              0   
..                           ...   
172                            0   
173                            1   
174                            1   
175                            1   
176                            1   

     Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs)   \
0                                                  NaN           
1                                                  NaN           
2                                                  NaN           
3                                                  NaN           
4                                                  NaN           
..                                                 ...           
172                                                1.0           
173                                                2.0           
174                                                2.0           
175                                                1.0           
176                                                2.0           

     Tratamento_Antidepressivo (0 - não, 1 - sim)  TPM_use (0 - não, 1 - sim)  \
0                                             0.0                         NaN   
1                                             0.0                         NaN   
2                                             0.0                         NaN   
3                                             0.0                         NaN   
4                                             0.0                         NaN   
..                                            ...                         ...   
172                                           0.0                         0.0   
173                                           0.0                         0.0   
174                                           1.0                         0.0   
175                                           0.0                         0.0   
176                                           0.0                         0.0   

     VLP_use (0 - não, 1 - sim)  CBZ_use (0 - não, 1 - sim)  \
0

In [161]:
dt.columns

Index(['ID_number',
       'GroupAED (1 - controles, 2 - responsivos, 3 - resistentes)',
       'SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)',
       'Depressão (0 - não, 1 - sim)',
       'Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs) ',
       'Tratamento_Antidepressivo (0 - não, 1 - sim)',
       'TPM_use (0 - não, 1 - sim)', 'VLP_use (0 - não, 1 - sim)',
       'CBZ_use (0 - não, 1 - sim)', 'CLB_use (0 - não, 1 - sim)',
       'PHT_use (0 - não, 1 - sim)', 'PHB_use (0 - não, 1 - sim)',
       'LMT_use (0 - não, 1 - sim)', 'LCS_use (0 - não, 1 - sim)',
       'CLZ_use (0 - não, 1 - sim)', 'OXC_use (0 - não, 1 - sim)',
       'LVT_USE (0 - não, 1 - sim)', 'BLOQ_SODIO_RAP', 'BLOQ_SOD_LENTO',
       'POTEN_GABA', 'PROT_SIN', 'ANTI-GLU', 'ipsiCR', 'ipsiGLU', 'ipsiINS',
       'ipsiNAA', 'ipsiGUA', 'ipsiGPCt', 'ipsiNAAt', 'ipsiCRt', 'ipsiGLX',
       'ipsiMM09', 'ipsiMM20', 'ipsiMM17', 'contraCR', 'contraGLU',
       'contraINS', 'contraNAA', 'contraGUA', 'contr

In [162]:
qntf = ['ipsiCR', 'ipsiGLU', 'ipsiINS','ipsiNAA', 'ipsiGUA', 'ipsiGPCt','ipsiNAAt','ipsiCRt','ipsiGLX','ipsiMM09','ipsiMM20','ipsiMM17','contraCR','contraGLU','contraINS','contraNAA', 'contraGUA', 'contraGPCt', 'contraNAAt','contraCRt', 'contraGlX', 'contraMM09', 'contraMM20', 'contraMM17','Vol_Ipsi_med_ctrls', 'Vol_contra_med_ctrls', 'BDNF', 'IL6', 'IL1b','IL8', 'TNFa']
farmacos = ['Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs) ','TPM_use (0 - não, 1 - sim)', 'VLP_use (0 - não, 1 - sim)','CBZ_use (0 - não, 1 - sim)','CLB_use (0 - não, 1 - sim)','PHT_use (0 - não, 1 - sim)','PHB_use (0 - não, 1 - sim)','LMT_use (0 - não, 1 - sim)','LCS_use (0 - não, 1 - sim)','CLZ_use (0 - não, 1 - sim)','OXC_use (0 - não, 1 - sim)','LVT_USE (0 - não, 1 - sim)']

Colocando valor de ID_number = 999 para paciente que veio com esse valor faltando

In [163]:
dt.iloc[148, 0] = 999
dt[dt.index.isna()]

Empty DataFrame
Columns: [ID_number, GroupAED (1 - controles, 2 - responsivos, 3 - resistentes), SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL), Depressão (0 - não, 1 - sim), Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs) , Tratamento_Antidepressivo (0 - não, 1 - sim), TPM_use (0 - não, 1 - sim), VLP_use (0 - não, 1 - sim), CBZ_use (0 - não, 1 - sim), CLB_use (0 - não, 1 - sim), PHT_use (0 - não, 1 - sim), PHB_use (0 - não, 1 - sim), LMT_use (0 - não, 1 - sim), LCS_use (0 - não, 1 - sim), CLZ_use (0 - não, 1 - sim), OXC_use (0 - não, 1 - sim), LVT_USE (0 - não, 1 - sim), BLOQ_SODIO_RAP, BLOQ_SOD_LENTO, POTEN_GABA, PROT_SIN, ANTI-GLU, ipsiCR, ipsiGLU, ipsiINS, ipsiNAA, ipsiGUA, ipsiGPCt, ipsiNAAt, ipsiCRt, ipsiGLX, ipsiMM09, ipsiMM20, ipsiMM17, contraCR, contraGLU, contraINS, contraNAA, contraGUA, contraGPCt, contraNAAt, contraCRt, contraGlX, contraMM09, contraMM20, contraMM17, Vol_Ipsi_med_ctrls, Vol_contra_med_ctrls, BDNF, IL6, IL1b, IL8, TNFa]
Index: []

[0 rows x 53 columns]

In [164]:
idx_labels_controle = dt.index[dt['GroupAED (1 - controles, 2 - responsivos, 3 - resistentes)'] == 1]

In [165]:
z_scores = np.array([])
for column in dt[qntf]:
    stand_d = dt[column].loc[idx_labels_controle].dropna().std(ddof=0)
    #print(especFarm[column].loc[idx_labels_controle])
    m = dt[column].loc[idx_labels_controle].dropna().mean()
    print(column, 'mean = ', m, 'stand_d = ', stand_d)
    if stand_d != 0:
        z_score = ((dt[column].dropna() - m)/stand_d)
        
        z_score = z_score.dropna()
        
        for i, z in z_score.iteritems():
            if z < 2 and z > -2:
                dt.loc[i,column] = 0
            elif z >= 2:
                dt.loc[i, column] = 1
            else:
                dt.loc[i, column] = -1
        
        
    else:
        dt[column] = 0

ipsiCR mean =  0.9616770833333333 stand_d =  0.0868929831257568
ipsiGLU mean =  1.209714285714286 stand_d =  0.15176818386161528
ipsiINS mean =  1.14401 stand_d =  0.1099015236473089
ipsiNAA mean =  0.7489673913043479 stand_d =  0.13554621392936805
ipsiGUA mean =  0.470163043478261 stand_d =  0.06905291404831028
ipsiGPCt mean =  0.32413 stand_d =  0.03263691315060296
ipsiNAAt mean =  0.9644900000000003 stand_d =  0.12378026862145677
ipsiCRt mean =  1.0 stand_d =  0.0
ipsiGLX mean =  1.88806 stand_d =  0.3464543785262354
ipsiMM09 mean =  0.8343586956521739 stand_d =  0.17536061177903112
ipsiMM20 mean =  2.374819444444445 stand_d =  0.4024072383236252
ipsiMM17 mean =  1.1065142857142856 stand_d =  0.2540378342383075
contraCR mean =  0.9616770833333333 stand_d =  0.0868929831257568
contraGLU mean =  1.209714285714286 stand_d =  0.15176818386161528
contraINS mean =  1.14401 stand_d =  0.1099015236473089
contraNAA mean =  0.7489673913043479 stand_d =  0.13554621392936805
contraGUA mean =  0

In [166]:
dt = dt.fillna(9999)
dt[qntf]

ipsiCR  ipsiGLU  ipsiINS  ipsiNAA  ipsiGUA  ipsiGPCt  ipsiNAAt  ipsiCRt  \
0       0.0      0.0      0.0      0.0      0.0      -1.0       0.0        0   
1       0.0      0.0      0.0   9999.0      0.0       0.0       0.0        0   
2       0.0      0.0      0.0      0.0      0.0       0.0       0.0        0   
3       0.0      0.0      0.0      0.0      0.0       0.0       0.0        0   
4       0.0   9999.0      0.0   9999.0      0.0       0.0      -1.0        0   
..      ...      ...      ...      ...      ...       ...       ...      ...   
172     0.0      0.0      1.0      0.0      0.0       0.0      -1.0        0   
173     0.0      0.0      1.0   9999.0      0.0       0.0       0.0        0   
174     0.0      0.0      1.0      0.0   9999.0       0.0       0.0        0   
175     0.0      0.0      1.0      0.0      0.0       0.0      -1.0        0   
176  9999.0      0.0      0.0   9999.0      0.0       0.0    9999.0        0   

     ipsiGLX  ipsiMM09  ...  contraMM09  contraMM20  contraMM17  \
0        0.0       0.0  ...         0.0         0.0      9999.0   
1        0.0       0.0  ...         0.0      9999.0      9999.0   
2        0.0       0.0  ...         0.0         0.0         0.0   
3        0.0       0.0  ...         0.0         0.0         0.0   
4        0.0       1.0  ...         1.0         0.0         0.0   
..       ...       ...  ...         ...         ...         ...   
172      0.0       0.0  ...         0.0         0.0      9999.0   
173      0.0       0.0  ...         0.0         0.0      9999.0   
174      0.0      -1.0  ...         0.0      9999.0      9999.0   
175      0.0       0.0  ...         0.0         0.0         0.0   
176      0.0       0.0  ...         0.0         0.0         0.0   

     Vol_Ipsi_med_ctrls  Vol_contra_med_ctrls    BDNF     IL6    IL1b     IL8  \
0                   0.0                   0.0  9999.0  9999.0  9999.0  9999.0   
1                   0.0                   0.0  9999.0  9999.0  9999.0  9999.0   
2                   0.0                   0.0     0.0     0.0     0.0     0.0   
3                   0.0                   0.0     0.0     0.0     0.0     0.0   
4                   0.0                   0.0     0.0     0.0     0.0     0.0   
..                  ...                   ...     ...     ...     ...     ...   
172                -1.0                   0.0     0.0     0.0     0.0     0.0   
173                -1.0                   0.0     0.0     0.0     0.0     0.0   
174                -1.0                   0.0  9999.0  9999.0  9999.0  9999.0   
175                 0.0                   0.0     0.0     0.0     0.0     0.0   
176                -1.0                   0.0     0.0     0.0     0.0     0.0   

       TNFa  
0    9999.0  
1    9999.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
172     0.0  
173     0.0  
174  9999.0  
175     0.0  
176     0.0  

[177 rows x 31 columns]

In [27]:
dt[qntf].to_csv('quantificacao_alterado.csv')

In [167]:
discretize_cols = ['SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)', 'Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs) ', 'ipsiCR', 'ipsiGLU', 'ipsiINS', 'ipsiNAA', 'ipsiGUA', 'ipsiGPCt', 'ipsiNAAt', 'ipsiCRt', 'ipsiGLX', 'ipsiMM09', 'ipsiMM20', 'ipsiMM17', 'contraCR', 'contraGLU', 'contraINS', 'contraNAA', 'contraGUA', 'contraGPCt', 'contraNAAt', 'contraCRt', 'contraGlX', 'contraMM09', 'contraMM20', 'contraMM17', 'Vol_Ipsi_med_ctrls', 'Vol_contra_med_ctrls', 'BDNF', 'IL6', 'IL1b', 'IL8', 'TNFa']
binary_cols = ['Depressão (0 - não, 1 - sim)','Tratamento_Antidepressivo (0 - não, 1 - sim)','BLOQ_SODIO_RAP', 'BLOQ_SOD_LENTO','POTEN_GABA', 'PROT_SIN', 'ANTI-GLU']
dt.loc[:,binary_cols] = dt.loc[:,binary_cols].fillna(0)
dt.loc[:,farmacos] = dt.loc[:,farmacos].fillna(0)
dt = dt.fillna(9999)

In [168]:
uniques = dt['SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)'].unique().astype('int')
uniques = np.delete(uniques, np.where(uniques == 0))
uniques

array([   1, 9999,    2,    3,    4])

In [169]:
dt.loc[dt['Depressão (0 - não, 1 - sim)'] == ' ']

ID_number  GroupAED (1 - controles, 2 - responsivos, 3 - resistentes)  \
163      169.0                                                  3            

     SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)  \
163                                                4.0            

    Depressão (0 - não, 1 - sim)  \
163                                

     Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs)   \
163                                             9999.0           

     Tratamento_Antidepressivo (0 - não, 1 - sim)  TPM_use (0 - não, 1 - sim)  \
163                                        9999.0                      9999.0   

     VLP_use (0 - não, 1 - sim)  CBZ_use (0 - não, 1 - sim)  \
163                      9999.0                      9999.0   

     CLB_use (0 - não, 1 - sim)  ...  contraMM09  contraMM20  contraMM17  \
163                      9999.0  ...         0.0         0.0         0.0   

     Vol_Ipsi_med_ctrls  Vol_contra_med_ctrls    BDNF     IL6    IL1b     IL8  \
163              9999.0                9999.0  9999.0  9999.0  9999.0  9999.0   

       TNFa  
163  9999.0  

[1 rows x 53 columns]

In [170]:
dt.iloc[163, 3] = 0
dt.loc[dt['Depressão (0 - não, 1 - sim)'] == ' ']

Empty DataFrame
Columns: [ID_number, GroupAED (1 - controles, 2 - responsivos, 3 - resistentes), SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL), Depressão (0 - não, 1 - sim), Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs) , Tratamento_Antidepressivo (0 - não, 1 - sim), TPM_use (0 - não, 1 - sim), VLP_use (0 - não, 1 - sim), CBZ_use (0 - não, 1 - sim), CLB_use (0 - não, 1 - sim), PHT_use (0 - não, 1 - sim), PHB_use (0 - não, 1 - sim), LMT_use (0 - não, 1 - sim), LCS_use (0 - não, 1 - sim), CLZ_use (0 - não, 1 - sim), OXC_use (0 - não, 1 - sim), LVT_USE (0 - não, 1 - sim), BLOQ_SODIO_RAP, BLOQ_SOD_LENTO, POTEN_GABA, PROT_SIN, ANTI-GLU, ipsiCR, ipsiGLU, ipsiINS, ipsiNAA, ipsiGUA, ipsiGPCt, ipsiNAAt, ipsiCRt, ipsiGLX, ipsiMM09, ipsiMM20, ipsiMM17, contraCR, contraGLU, contraINS, contraNAA, contraGUA, contraGPCt, contraNAAt, contraCRt, contraGlX, contraMM09, contraMM20, contraMM17, Vol_Ipsi_med_ctrls, Vol_contra_med_ctrls, BDNF, IL6, IL1b, IL8, TNFa]
Index: []

[0 rows x 53 columns]

In [171]:
print('contraNAAt = ', dt['contraNAAt'].unique() )
print('ipsiNAAt = ', dt['ipsiNAAt'].unique() )   
print('contraINS = ', dt['contraINS'].unique() ) 
print('ipsiINS = ', dt['ipsiINS'].unique() ) 
print('contraGLU = ', dt['contraGLU'].unique() )
print('ipsiGLU = ', dt['ipsiGLU'].unique() )
print('contraGPCt = ', dt['contraGPCt'].unique() ) 
print('ipsiGPCt = ', dt['ipsiGPCt'].unique() )   
print('Vol_contra_med_ctrls = ', dt['Vol_contra_med_ctrls'].unique() ) 
print('Vol_Ipsi_med_ctrls = ', dt['Vol_Ipsi_med_ctrls'].unique() ) 

contraNAAt =  [ 0.000e+00 -1.000e+00  9.999e+03]
ipsiNAAt =  [ 0.000e+00 -1.000e+00  9.999e+03]
contraINS =  [ 0.000e+00  1.000e+00 -1.000e+00  9.999e+03]
ipsiINS =  [ 0.000e+00  1.000e+00 -1.000e+00  9.999e+03]
contraGLU =  [ 0.000e+00  9.999e+03  1.000e+00 -1.000e+00]
ipsiGLU =  [ 0.000e+00  9.999e+03  1.000e+00 -1.000e+00]
contraGPCt =  [-1.000e+00  0.000e+00  1.000e+00  9.999e+03]
ipsiGPCt =  [-1.000e+00  0.000e+00  1.000e+00  9.999e+03]
Vol_contra_med_ctrls =  [ 0.000e+00  1.000e+00  9.999e+03 -1.000e+00]
Vol_Ipsi_med_ctrls =  [ 0.000e+00  1.000e+00 -1.000e+00  9.999e+03]


In [154]:
dt[dt['ipsiNAA'] == 1].index

Int64Index([69], dtype='int64')

In [172]:
dt.iloc[dt[dt['contraINS'] < 0].index,dt.columns.get_loc("contraINS")] = 9999
print('contraINS = ', dt['contraINS'].unique() )

dt.iloc[dt[dt['ipsiINS'] < 0].index,dt.columns.get_loc("ipsiINS")] = 9999
print('ipsiINS = ', dt['ipsiINS'].unique() )

dt.iloc[dt[dt['contraGPCt'] < 0].index,dt.columns.get_loc("contraGPCt")] = 9999
print('contraGPCt = ', dt['contraGPCt'].unique() )

dt.iloc[dt[dt['ipsiGPCt'] < 0].index,dt.columns.get_loc("ipsiGPCt")] = 9999
print('ipsiGPCt = ', dt['ipsiGPCt'].unique() )

dt.iloc[dt[dt['Vol_contra_med_ctrls'] == 1].index,dt.columns.get_loc("Vol_contra_med_ctrls")] = 9999
print('Vol_contra_med_ctrls = ', dt['Vol_contra_med_ctrls'].unique() )

dt.iloc[dt[dt['Vol_Ipsi_med_ctrls'] == 1].index,dt.columns.get_loc("Vol_Ipsi_med_ctrls")] = 9999
print('Vol_Ipsi_med_ctrls = ', dt['Vol_Ipsi_med_ctrls'].unique() )

contraINS =  [0.000e+00 1.000e+00 9.999e+03]
ipsiINS =  [0.000e+00 1.000e+00 9.999e+03]
contraGPCt =  [9.999e+03 0.000e+00 1.000e+00]
ipsiGPCt =  [9.999e+03 0.000e+00 1.000e+00]
Vol_contra_med_ctrls =  [ 0.000e+00  9.999e+03 -1.000e+00]
Vol_Ipsi_med_ctrls =  [ 0.000e+00  9.999e+03 -1.000e+00]


In [176]:
new_cols = [
       'SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)',
       'Depressão (0 - não, 1 - sim)',
       'Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs) ',
       'Tratamento_Antidepressivo (0 - não, 1 - sim)',
       'BLOQ_SODIO_RAP', 'BLOQ_SOD_LENTO',
       'POTEN_GABA', 'PROT_SIN', 'ANTI-GLU', 'ipsiGLU', 'ipsiINS',
       'ipsiGPCt', 'ipsiNAAt', 'contraGLU',
       'contraINS', 'contraGPCt', 'contraNAAt',
       'Vol_Ipsi_med_ctrls', 'Vol_contra_med_ctrls']
dt_no_contrl = dt.iloc[50:,:]
dt_no_contrl[new_cols]

SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)  \
50                                              9999.0            
51                                                 2.0            
52                                                 2.0            
53                                                 2.0            
54                                                 2.0            
..                                                 ...            
172                                                4.0            
173                                                4.0            
174                                                4.0            
175                                                4.0            
176                                                4.0            

    Depressão (0 - não, 1 - sim)  \
50                          9999   
51                             1   
52                             0   
53                             1   
54                             1   
..                           ...   
172                            0   
173                            1   
174                            1   
175                            1   
176                            1   

     Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs)   \
50                                                 2.0           
51                                                 2.0           
52                                                 1.0           
53                                                 2.0           
54                                                 1.0           
..                                                 ...           
172                                                1.0           
173                                                2.0           
174                                                2.0           
175                                                1.0           
176                                                2.0           

     Tratamento_Antidepressivo (0 - não, 1 - sim)  BLOQ_SODIO_RAP  \
50                                            0.0             1.0   
51                                            0.0             1.0   
52                                            0.0             1.0   
53                                            1.0             1.0   
54                                         9999.0             1.0   
..                                            ...             ...   
172                                           0.0             1.0   
173                                           0.0             1.0   
174                                           1.0             0.0   
175                                           0.0             1.0   
176                                           0.0             1.0   

     BLOQ_SOD_LENTO  POTEN_GABA  PROT_SIN  ANTI-GLU  ipsiGLU  ipsiINS  \
50              0.0         1.0       0.0       1.0      0.0      0.0   
51              0.0         1.0       0.0       0.0      0.0      0.0   
52              0.0         0.0       0.0       0.0      0.0      0.0   
53              0.0         1.0       0.0       0.0   9999.0   9999.0   
54              0.0         0.0       0.0       0.0      0.0      0.0   
..              ...         ...       ...       ...      ...      ...   
172             0.0         0.0       0.0       0.0      0.0      1.0   
173             0.0         1.0       0.0       0.0      0.0      1.0   
174             1.0         1.0       0.0       0.0      0.0      1.0   
175             0.0         0.0       0.0       0.0      0.0      1.0   
176             0.0         1.0       0.0       0.0      0.0      0.0   

     ipsiGPCt  ipsiNAAt  contraGLU  contraINS  contraGPCt  contraNAAt  \
50        0.0       0.0       -1.0     9999.0         0.0         0.0   
51        0.0       0.0       -1.0        0.0         0.0         0.0   
52        0.0       0.0        0.0        0.0    

Binarizando a classe

In [181]:
label = dt.iloc[50:,1]
label[label == 3] = 1
label[label == 2] = 0

In [182]:
new_dt = pd.concat([dt_no_contrl[new_cols], dt.iloc[50:,1]], axis=1)
new_dt.astype('int')

SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)  \
50                                                9999            
51                                                   2            
52                                                   2            
53                                                   2            
54                                                   2            
..                                                 ...            
172                                                  4            
173                                                  4            
174                                                  4            
175                                                  4            
176                                                  4            

     Depressão (0 - não, 1 - sim)  \
50                           9999   
51                              1   
52                              0   
53                              1   
54                              1   
..                            ...   
172                             0   
173                             1   
174                             1   
175                             1   
176                             1   

     Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs)   \
50                                                   2           
51                                                   2           
52                                                   1           
53                                                   2           
54                                                   1           
..                                                 ...           
172                                                  1           
173                                                  2           
174                                                  2           
175                                                  1           
176                                                  2           

     Tratamento_Antidepressivo (0 - não, 1 - sim)  BLOQ_SODIO_RAP  \
50                                              0               1   
51                                              0               1   
52                                              0               1   
53                                              1               1   
54                                           9999               1   
..                                            ...             ...   
172                                             0               1   
173                                             0               1   
174                                             1               0   
175                                             0               1   
176                                             0               1   

     BLOQ_SOD_LENTO  POTEN_GABA  PROT_SIN  ANTI-GLU  ipsiGLU  ipsiINS  \
50                0           1         0         1        0        0   
51                0           1         0         0        0        0   
52                0           0         0         0        0        0   
53                0           1         0         0     9999     9999   
54                0           0         0         0        0        0   
..              ...         ...       ...       ...      ...      ...   
172               0           0         0         0        0        1   
173               0           1         0         0        0        1   
174               1           1         0         0        0        1   
175               0           0         0         0        0        1   
176               0           1         0         0        0        0   

     ipsiGPCt  ipsiNAAt  contraGLU  contraINS  contraGPCt  contraNAAt  \
50          0         0         -1       9999           0           0   
51          0         0         -1          0           0           0   
52          0         0          0   

Preparando para inclose5

In [11]:
df = pd.read_csv('Espectros_farmacos_5classes_sumarizado_categorico.csv')
df

SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)  \
0                                                 9999            
1                                                    2            
2                                                    2            
3                                                    2            
4                                                    2            
..                                                 ...            
122                                                  4            
123                                                  4            
124                                                  4            
125                                                  4            
126                                                  4            

     Depressão (0 - não, 1 - sim)  \
0                            9999   
1                               1   
2                               0   
3                               1   
4                               1   
..                            ...   
122                             0   
123                             1   
124                             1   
125                             1   
126                             1   

     Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs)   \
0                                                    2           
1                                                    2           
2                                                    1           
3                                                    2           
4                                                    1           
..                                                 ...           
122                                                  1           
123                                                  2           
124                                                  2           
125                                                  1           
126                                                  2           

     Tratamento_Antidepressivo (0 - não, 1 - sim)  BLOQ_SODIO_RAP  \
0                                               0               1   
1                                               0               1   
2                                               0               1   
3                                               1               1   
4                                            9999               1   
..                                            ...             ...   
122                                             0               1   
123                                             0               1   
124                                             1               0   
125                                             0               1   
126                                             0               1   

     BLOQ_SOD_LENTO  POTEN_GABA  PROT_SIN  ANTI-GLU  ipsiGLU  ipsiINS  \
0                 0           1         0         1        0        0   
1                 0           1         0         0        0        0   
2                 0           0         0         0        0        0   
3                 0           1         0         0     9999     9999   
4                 0           0         0         0        0        0   
..              ...         ...       ...       ...      ...      ...   
122               0           0         0         0        0        1   
123               0           1         0         0        0        1   
124               1           1         0         0        0        1   
125               0           0         0         0        0        1   
126               0           1         0         0        0        0   

     ipsiGPCt  ipsiNAAt  contraGLU  contraINS  contraGPCt  contraNAAt  \
0           0         0         -1       9999           0           0   
1           0         0         -1          0           0           0   
2           0         0          0   

In [20]:
discretize_cols = ['SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)', 
                   'Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs) ', 
                   'ipsiGLU', 'contraGLU']
binary_cols = ['Depressão (0 - não, 1 - sim)','Tratamento_Antidepressivo (0 - não, 1 - sim)',
                             'BLOQ_SODIO_RAP', 'BLOQ_SOD_LENTO','POTEN_GABA', 'PROT_SIN', 'ANTI-GLU', 'ipsiINS',
                             'ipsiGPCt', 'contraINS', 'contraGPCt']

new_data = np.array([])
new_cols2 = []
n_rows = len(df)
for column in df.iloc[:,:-1]:
    if column in binary_cols:
        col = df[column].replace(9999, 0).to_numpy(dtype='int').reshape((n_rows, 1))
        #print('col = ', df[column].to_numpy(dtype='int').reshape((n_rows, 1)))
        new_data = np.concatenate((new_data, col), axis=1)
        new_cols2 += [column]
        
    else:
        uniques = df[column].unique().astype('int')
        print(uniques)
        uniques = np.delete(uniques, np.where(uniques == 9999))
        uniques = np.delete(uniques, np.where(uniques == 0))
            

        print(column, ' = ', len(uniques), uniques)
        aux = np.zeros((n_rows,len(uniques)), dtype=int)
        for i, value in df[column].iteritems():
            for j in range(len(uniques)):
                if value == uniques[j]:
                    aux[i,j] = 1
                else:
                    aux[i,j] = 0

        if new_data.size:
            new_data = np.concatenate((new_data, aux), axis=1)
        else:
            new_data = aux


        for j in uniques:
            new_cols2 += [column+str(j)]
                
    

        
print(new_data.shape)
print(new_cols2)

[9999    2    3    4]
SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)  =  3 [2 3 4]
[   2    1    0 9999]
Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs)   =  2 [2 1]
[   0 9999    1   -1]
ipsiGLU  =  2 [ 1 -1]
[   0 9999   -1]
ipsiNAAt  =  1 [-1]
[  -1    0    1 9999]
contraGLU  =  2 [-1  1]
[   0   -1 9999]
contraNAAt  =  1 [-1]
[   0 9999   -1]
Vol_Ipsi_med_ctrls  =  1 [-1]
[   0 9999   -1]
Vol_contra_med_ctrls  =  1 [-1]
(127, 24)
['SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)2', 'SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)3', 'SideHS (1 - controles, 2 - MRI-negativa, 3 - AHD, 4 - AHL)4', 'Depressão (0 - não, 1 - sim)', 'Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs) 2', 'Regimen (0 - sem DAEs, 1 - uma DAES, 3 - 2 ou mais DAEs) 1', 'Tratamento_Antidepressivo (0 - não, 1 - sim)', 'BLOQ_SODIO_RAP', 'BLOQ_SOD_LENTO', 'POTEN_GABA', 'PROT_SIN', 'ANTI-GLU', 'ipsiGLU1', 'ipsiGLU-1', 'ipsiINS', 'ipsiGPCt', 'ipsiNAAt-1', 'contraGLU-

In [21]:
np.savetxt('Espectros_farmacos_5classes_sumarizado_binario', new_data, fmt='%d')

In [16]:
df.iloc[:,-1]

0      0
1      0
2      0
3      0
4      0
      ..
122    1
123    1
124    1
125    1
126    1
Name: GroupAED (1 - controles, 2 - responsivos, 3 - resistentes), Length: 127, dtype: int64

In [10]:
np.savetxt('Espectros_farmacos_5classes_sumarizado_binario_col0_col1_labels', df.iloc[:,-1], fmt='%d')